kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "gorrino.fullname" . }}-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "gorrino.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "gorrino.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
